name: Minecraft Server CI/CD

on:
  push:
    branches:
      - main

jobs:
  update_server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH for EC2 Access
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.MINECRAFT_SERVER }}

    - name: Update Minecraft Server and Restart Service
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@3.145.20.30 "sudo ./minecraft-setup.sh && sudo systemctl restart minecraft.service"
